WITH CTE1 AS 
(
    SELECT ID, MAX(STL_PRODART) AS MAKSART, MIN(POS_NR) AS MAXPOS
    FROM [dbo].[ALFAK_STKL_DG]
    WHERE STL_PRODART IN (1, 2) 
    GROUP BY ID
)SELECT q2.ID,
		q2.POS_NR,
		q2.STL_BEZ,
		q2.STL_PRODART,
		q2.STL_PRODGRP,
		q2.BOM_NODE,
		q2.BOM_LEVEL,
		q2.BIRIM,
		q2.BOM_ID,
		q2.BIRIMFIYAT,
		q2.HESAPLANMISFIYAT,
		q2.DATUM_ERF,
		q2.ROWID,
		q2.BOM_PRODUKT
			
			FROM (
			SELECT *,	
				ROW_NUMBER() OVER (PARTITION BY Q1.ID,Q1.POS_NR,Q1.BOM_ID,Q1.BOM_NODE ORDER BY Q1.RN) AS RN2 
			FROM 
			(
				SELECT 
				STKL.ID,
				STKL.POS_NR,
				STKL.STL_BEZ ,
				STKL.STL_PRODART,
				STKL.STL_PRODGRP,
				STKL.BOM_ID,
				STKL.BOM_NODE,
				STKL.BOM_LEVEL,
				PR_MEEINHEIT AS BIRIM,
				VER_PREIS_ME AS BIRIMFIYAT,
				VER_NETTO_GES AS HESAPLANMISFIYAT,
				KOPF.DATUM_ERF,
				STKL.ROWID,
				STKL.BOM_PRODUKT,
				ROW_NUMBER() OVER (PARTITION BY STKL.ID ORDER BY STKL.ID) AS RN

				FROM [dbo].[ALFAK_STKL_DG] AS STKL
				INNER JOIN CTE1 ON STKL.ID = CTE1.ID
				INNER JOIN [dbo].[ALFAK_KOPF_DG] AS KOPF ON STKL.ID=KOPF.ID

				WHERE 
				(	(STL_BIT=12 AND STL_PRODART IN (1,2, 30, 60, 10, 11, 12, 20, 40, 3) AND STL_MOD=1
					OR (STL_PRODART IN (1, 3, 10, 11, 12, 20, 30, 40, 60) AND STL_BEZ LIKE '%Lameks%') 							) 
		
					OR(
					STL_PRODART IN (CTE1.MAKSART, 30, 60, 10, 11, 12, 20, 40, 3)
					OR (STL_PRODART IN (1, 3, 10, 11, 12, 20, 30, 40, 60) AND STL_BEZ LIKE '%Lameks%')
				))
				AND POS_NR = CTE1.MAXPOS
				AND KOPF.DATUM_ERF >DATEADD(MONTH, -1, GETDATE())
				AND LEN(STKL.ID) > 4
				--AND STKL.ID=227500
				)Q1
				--ORDER BY Q1.ID,Q1.RN
				)Q2
				WHERE Q2.RN2=1
				ORDER BY Q2.ID,Q2.RN