SELECT Q2.GOREVNO,
		Q2.MUSTERI,
		Q2.KOMISYON,
		Q2.ÜRÜN,
		Q2.M2,
		Q2.ADET,
		--Q2.STATUS,
		

		CASE WHEN Q2.PARABIRIMI='TL' THEN BIRIMFIYAT
				
				ELSE null END AS BIRIMFIYAT_TL
		,CASE WHEN Q2.PARABIRIMI='EUR' THEN BIRIMFIYAT
				
				ELSE null END AS BIRIMFIYAT_EUR
		,CASE WHEN Q2.PARABIRIMI='USD' THEN BIRIMFIYAT
				
				ELSE null END AS BIRIMFIYAT_USD
	

FROM 
(
SELECT	Q1.ID AS GOREVNO,
		Q1.AH_NAME1 AS MUSTERI,
		Q1.POS_KOMMISSION AS KOMISYON,
		Q1.ÜRÜN,
		--Q1.STATUS,

		
		Q1.QM AS M2,
		Q1.TOPLAMFIYAT/QM AS BIRIMFIYAT,
		Q1.FI_WAEHRUNG AS PARABIRIMI,
		Q1.SU_STUECK AS ADET,
		Q1.TOPLAMFIYAT
FROM 
	(
	SELECT	K.ID,
	--K.STATUS,
			K.AH_NAME1,
			P.POS_KOMMISSION,
			--K.FI_BETR_NETTO/K.SU_QM_REAL as BIRIM,
			P.PROD_BEZ1+P.PROD_BEZ2+P.PROD_BEZ3 AS ÜRÜN,	
			CASE WHEN K.SU_QM_REAL=0 AND LEFT(K.ID,1)=4 THEN 1 ELSE K.SU_QM_REAL END AS QM,
			K.SU_QM_REAL,
			K.FI_BETR_NETTO AS TOPLAMFIYAT,
			K.FI_WAEHRUNG,
			K.SU_STUECK		
	FROM [dbo].[ALFAK_KOPF_DG] AS K INNER JOIN ALFAK_POS_DG AS P  ON K.ID=P.ID AND P.POS_NR=1
			WHERE K.DATUM_ERF=CAST(  GETDATE() AS DATE) AND K.AH_MCODE<>'TEST' AND (K.STATUS BETWEEN 1 AND 599 OR K.STATUS=810 OR K.STATUS=952)
	) Q1

	)Q2


