WITH CTE1 AS 
(
    SELECT ID, MAX(STL_PRODART) AS MAKSART, MIN(POS_NR) AS MAXPOS
    FROM [dbo].[ALFAK_STKL_DG]
    WHERE STL_PRODART IN (1, 2) 
    GROUP BY ID
)

SELECT 
    mainQuery.ID,mainQuery.CUSTOMER,mainQuery.TOTSQM,mainQuery.ENTRYDATE,mainQuery.QUANTITY,cast(mainQuery.ID as nvarchar)+cast(mainQuery.ENTRYDATE as nvarchar) as rowid,
    CAST((
	STUFF((
        SELECT '+ ' + Q1.ENG
        FROM ( SELECT Q2.*,KLM.ENG FROM
				(SELECT 
					STKL.ID,
					STKL.POS_NR,
					STKL.BOM_PRODUKT,
					ROW_NUMBER()OVER (PARTITION BY STKL.ID ORDER BY STKL.ID ) AS RN
					--STKL.STL_BEZ
				FROM [dbo].[ALFAK_STKL_DG] AS STKL
				INNER JOIN CTE1 ON STKL.ID = CTE1.ID 

				WHERE 
					STKL.ID = mainQuery.ID 
					AND
	(	(STL_BIT=12 AND STL_PRODART IN (1,2, 30, 60, 10, 11, 12, 20, 40, 3) AND STL_MOD=1
        OR (STL_PRODART IN (1, 3, 10, 11, 12, 20, 30, 40, 60) AND STL_BEZ LIKE '%Lameks%') 							) 
		
		OR(
        STL_PRODART IN (CTE1.MAKSART, 30, 60, 10, 11, 12, 20, 40, 3)
        OR (STL_PRODART IN (1, 3, 10, 11, 12, 20, 30, 40, 60) AND STL_BEZ LIKE '%Lameks%')
    ))			AND POS_NR = CTE1.MAXPOS) AS Q2
					INNER JOIN [dbo].[ALFAK_ENG_ITEM] AS KLM
					ON
					Q2.BOM_PRODUKT=KLM.Numara

        ) AS Q1 ORDER BY RN
        FOR XML PATH('')
    ), 1, 1, '')) AS VARCHAR(2500)) AS KOMBINASYON 
FROM (
		SELECT DISTINCT STKL2.ID,
						KOPF.AH_NAME1+AH_NAME2 AS CUSTOMER,
						CAST(KOPF.SU_QM_REAL AS decimal(8,2))  AS TOTSQM,
						CAST(KOPF.SU_STUECK AS INT) AS QUANTITY,
						KOPF.DATUM_ERF AS ENTRYDATE
						



		FROM [dbo].[ALFAK_STKL_DG] AS STKL2 INNER JOIN [dbo].[ALFAK_KOPF_DG] AS KOPF
		ON
		STKL2.ID=KOPF.ID
	WHERE KOPF.DATUM_ERF >DATEADD(MONTH, -5, GETDATE())


) AS mainQuery
--WHERE mainQuery.ID=226995

ORDER BY ENTRYDATE DESC