USE [DOGUKANSSIS]
GO

/****** Object:  StoredProcedure [dbo].[PROFIL_IHTIYAC]    Script Date: 23.03.2024 21:58:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


    CREATE PROCEDURE [dbo].[PROFIL_IHTIYAC]
    @Baslangýc date,
	@býtýs date,
	@durum1 INT,
	@durum2 INT
AS
SELECT  

 PR.TANIMLAMA,CAST( SUM(T.SU_LFM_REAL) AS DECIMAL(8,2)) AS METRETUL
  FROM TEMELLI_ISICAM_W AS T
  INNER JOIN [dbo].[KALEM_PROFIL] AS PR
  ON
  T.BOM_PRODUKT=PR.NUMARA
  WHERE T.DATUM_ERF BETWEEN @Baslangýc AND @býtýs
  AND T.STATUS BETWEEN @durum1 and @durum2
  GROUP BY PR.TANIMLAMA
GO


