USE [DOGUKANSSIS]
GO

/****** Object:  View [dbo].[TEMELLI_ISICAM_W]    Script Date: 23.03.2024 21:55:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW  [dbo].[TEMELLI_ISICAM_W] AS

WITH CTE1 AS 
(
    SELECT ID,  MIN(POS_NR) AS MAXPOS
    FROM [dbo].[ALFAK_POS_DG]

    GROUP BY ID
)
SELECT AUFNR,BOM_PRODUKT,SU_LFM_FAKT,SU_LFM_REAL,DATUM_ERF,MUSTERI,SU_QM_FAKT,SU_QM_REAL,RN,SU_GEWICHT,STATUS 
	FROM 
	(
SELECT	Z.AUFNR,
		STKL.BOM_PRODUKT,

		K.SU_LFM_FAKT,
		K.SU_LFM_REAL,
		K.DATUM_ERF,
		K.AH_NAME1 AS MUSTERI,
		K.SU_QM_FAKT,
		K.SU_QM_REAL,
		ROW_NUMBER() OVER (PARTITION BY Z.AUFNR,STKL.BOM_PRODUKT ORDER BY Z.AUFNR) AS RN,
		K.SU_GEWICHT,
		K.STATUS

		
  FROM [dbo].[ALFAK_AUFTR_ZEIT_DG] AS Z
  INNER JOIN [dbo].[ALFAK_KOPF_DG] AS K
  ON Z.AUFNR = K.ID
  INNER JOIN CTE1 ON K.ID=CTE1.ID
  INNER JOIN [dbo].[ALFAK_STKL_DG] AS STKL ON Z.AUFNR=STKL.ID

  WHERE 

  Z.POSNR=1
  AND Z.AGG=1131
  AND CTE1.MAXPOS=Z.POSNR 
  AND Z.KZ_SELECTED=1


  )Q1
  WHERE RN=1
GO


