USE [DOGUKANSSIS]
GO

/****** Object:  StoredProcedure [dbo].[PROFIL_IHTIYAC_DETAYLI]    Script Date: 23.03.2024 21:58:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


/****** Script for SelectTopNRows command from SSMS  ******/

CREATE PROCEDURE [dbo].[PROFIL_IHTIYAC_DETAYLI]
    @Baslangýc date,
	@býtýs date,
	@durum1 INT,
	@durum2 INT
AS
SELECT	AUFNR AS GOREVNO,
		DATUM_ERF AS TARIH,
		BOM_PRODUKT AS KALEM,
		TANIMLAMA AS CITA,
		SU_LFM_REAL AS METRETUL_REEL,
		SU_LFM_FAKT AS METRETULLBRUT,
		MUSTERI,
		STATUS AS DURUM
		
		
  FROM TEMELLI_ISICAM_W AS T
  INNER JOIN KALEM_PROFIL AS K
  ON
  T.BOM_PRODUKT=K.NUMARA
WHERE T.DATUM_ERF BETWEEN @Baslangýc AND @býtýs
  AND T.STATUS BETWEEN @durum1 and @durum2
GO


